# Generated by Django 5.2.7 on 2025-10-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('sport', models.CharField(choices=[('Fútbol', 'Futbol'), ('Baloncesto', 'Baloncesto'), ('Voleibol', 'Voleibol'), ('Tenis de Mesa', 'Tenis De Mesa')], max_length=20, verbose_name='Deporte')),
                ('format', models.CharField(max_length=20, verbose_name='Formato')),
                ('max_teams', models.PositiveIntegerField(verbose_name='Equipos máximos')),
                ('current_teams', models.PositiveIntegerField(default=0, verbose_name='Equipos inscritos')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('phase', models.CharField(default='Planificación', max_length=30, verbose_name='Fase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
